from .models import (
    Base,
    BotConfig,
    ServerSettings,
    LastFMusers,
    UserTimezone,
    UserLocation,
    FavoriteSongs,
    CaseNote,
    LastFMvotes,
    Punishment,
    PunishmentType,
    WatchdogLog,
    JailedUser,
    CommandStatus,
    CommandCooldown,
    CommandUsageDaily,
    CommandLatencyDaily,
    CommandErrorDaily,
    DailyUserExposure,
    Blacklist,
    BoosterRole,
    Transaction,
    CryptoAsset,
    CryptoPrice,
    Supply,
    EconomicMetricsHistory,
    UserEconomicPreferences,
    Reputation,
    Wallet,
    Block,
    Loan,
    LoanPayment,
    Item,
    ItemType,
    EffectType,
    ShopItem,
    ItemCooldown,
    ActiveEffect,
    TradeLog,
    Bounty,
    Skulls,
    Flames,
    Hearts,
    Clowns,
    Sobs,
    ReactionSettings,
    HeardleGameStats,
    GameHistory,
    GameSession,
    GameSessionEvent,
    UserRoleHistory,
    Task,
    JTCSettings,
    TempVoiceChannel,
    UserNameHistory,
    MinesSettings,
    LockdownChannel,
    Juul,
    UserAlt,
    OwnerAuditLog,
    Job,
    VIPTier,
    UserVIP,
    RakebackBalance,
    RakebackTransaction,
)
from .managers import (
    BaseManager,
    CoreMixin,
    GuildMixin,
    UserMixin,
    ModerationMixin,
    EconomyMixin,
    CasinoMixin,
    InventoryMixin,
    SocialMixin,
    MusicMixin,
)


class DatabaseManager(
    CoreMixin,
    GuildMixin,
    UserMixin,
    ModerationMixin,
    EconomyMixin,
    CasinoMixin,
    InventoryMixin,
    SocialMixin,
    MusicMixin,
    BaseManager,
):
    async def initialize(self):
        """Create tables and seed required runtime rows on a fresh database."""
        await super().initialize()
        # VIP tiers must exist before any game can record rakeback/UserVIP rows.
        await self.ensure_default_vip_tiers()
        # Economy supply record must exist for the circuit breaker and rebalancing.
        await self.initialize_supply_record()
